imports:
    - { resource: parameters.ini }
    - { resource: @HighlightBundle/Resources/config/config.yml }

# Symfony Configuration
framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        terrificrewrite:
            resource: %kernel.root_dir%/../vendor/bundles/Terrific/CoreBundle/Resources/config/terrificrewrite.xml
        lessphp:
            apply_to: "\.less$"
            file:   %kernel.root_dir%/../vendor/lessphp/lessc.inc.php

# Highlight Configuration
highlight:
    # Each provider in this list are use on after other
    # if language given in template ins't allowed
    providers: [ pygment ]

    globals:
        linenos: false
        blockstyles: ""
        cssclass: highlight

    pygment:
        linenos: false
        blockstyles: ""
        cssclass: pygment


