TerrificComposerCoreBundle:
    resource: "@TerrificComposerCoreBundle/Controller/"
    type:     annotation
    prefix:   /terrific/composer/

AcmeModuleDemoBundle:
    resource: "@AcmeModuleDemoBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
